services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    restart: always

  server:
    image: booboo531/chat-server
    container_name: chat-server
    ports:
      - "5000:5000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/chatdb
    depends_on:
      - mongo

  frontend:
    image: booboo531/chat-client   # <-- image của bạn, nhớ build và push lên DockerHub
    container_name: chat-client
    ports:
      - "3000:80"                    # map port: client dùng localhost:3000
    depends_on:
      - server
